# Generated by Django 4.1 on 2022-08-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
    ]
