# Generated by Django 4.1 on 2022-08-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField(unique=True)),
                ('cvv', models.IntegerField()),
                ('creation_date', models.TextField()),
                ('expire_date', models.TextField()),
                ('card_type', models.TextField()),
                ('brand', models.TextField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
